services:
  autorecon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autorecon-container
    volumes:
      - ../../output/autorecon:/results
    privileged: true
    network_mode: "host"